services:
  db:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    container_name: vericert-db
    restart: always
    environment:
      MYSQL_DATABASE: vericert
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    # CAMBIA in qualcosa di robusto
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # CAMBIA anche questo
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db_data:/var/lib/mysql
    networks:
      vericert-net:
        ipv4_address: 172.30.0.10
  app:
    env_file:
      - myenv.env
    build: .
    container_name: vericert-app
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    working_dir: /app
    environment:
      TZ: Europe/Rome
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Rome"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vericert?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Rome
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      # Stripe (placeholder: li metterai via .env)
      PAYMENTS_STRIPE_SECRET_KEY: ${PAYMENTS_STRIPE_SECRET_KEY}
      PAYMENTS_STRIPE_WEBHOOK_SECRET: ${PAYMENTS_STRIPE_WEBHOOK_SECRET}
      PAYMENTS_STRIPE_PUBLISHABLE_KEY: ${PAYMENTS_STRIPE_PUBLISHABLE_KEY}
      # PayPal
      PAYMENTS_PAYPAL_CLIENT_ID: ${PAYMENTS_PAYPAL_CLIENT_ID}
      PAYMENTS_PAYPAL_CLIENT_SECRET: ${PAYMENTS_PAYPAL_CLIENT_SECRET}
      PAYMENTS_PAYPAL_WEBHOOK_ID: ${PAYMENTS_PAYPAL_WEBHOOK_ID}

      # Base URL pubblica (per link nei certificati / QR)
      APP_PUBLIC_BASE_URL: https://app.vercert.org
      VERCERT_STORAGE_ROOT: /data/vericert
    networks:
      - vericert-net
    volumes:
      - /opt/vericert/storage:/app/storage
      - /opt/vericert:/data/vericert
  nginx:
    image: nginx:1.27-alpine
    container_name: vericert-nginx
    restart: always
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      # quando abiliterai HTTPS:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html/starting.html:/usr/share/nginx/html/starting.html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - vericert-net
networks:
  vericert-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
volumes:
  db_data:
  opt-vericert-storage: